package org.my.core.common.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.my.core.common.model.SysResources;
import org.my.core.common.model.SysResourcesExample;

public interface SysResourcesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    int countByExample(SysResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    int deleteByExample(SysResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    int insert(SysResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    int insertSelective(SysResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    List<SysResources> selectByExample(SysResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    SysResources selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    int updateByExampleSelective(@Param("record") SysResources record, @Param("example") SysResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    int updateByExample(@Param("record") SysResources record, @Param("example") SysResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    int updateByPrimaryKeySelective(SysResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    int updateByPrimaryKey(SysResources record);
}