package org.my.core.common.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.my.core.common.model.SysStyles;
import org.my.core.common.model.SysStylesExample;

public interface SysStylesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_styles
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    int countByExample(SysStylesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_styles
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    int deleteByExample(SysStylesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_styles
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_styles
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    int insert(SysStyles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_styles
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    int insertSelective(SysStyles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_styles
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    List<SysStyles> selectByExample(SysStylesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_styles
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    SysStyles selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_styles
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    int updateByExampleSelective(@Param("record") SysStyles record, @Param("example") SysStylesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_styles
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    int updateByExample(@Param("record") SysStyles record, @Param("example") SysStylesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_styles
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    int updateByPrimaryKeySelective(SysStyles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_styles
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    int updateByPrimaryKey(SysStyles record);
}