package org.my.core.common.model;

public class SysRoles {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.ID
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.NAME
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.MARK
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    private String mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.DESCRIPTION
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.ENABLED
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    private String enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.IS_SYS
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    private String isSys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_roles.MODULE_ID
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    private String moduleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.ID
     *
     * @return the value of sys_roles.ID
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.ID
     *
     * @param id the value for sys_roles.ID
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.NAME
     *
     * @return the value of sys_roles.NAME
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.NAME
     *
     * @param name the value for sys_roles.NAME
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.MARK
     *
     * @return the value of sys_roles.MARK
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.MARK
     *
     * @param mark the value for sys_roles.MARK
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.DESCRIPTION
     *
     * @return the value of sys_roles.DESCRIPTION
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.DESCRIPTION
     *
     * @param description the value for sys_roles.DESCRIPTION
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.ENABLED
     *
     * @return the value of sys_roles.ENABLED
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.ENABLED
     *
     * @param enabled the value for sys_roles.ENABLED
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public void setEnabled(String enabled) {
        this.enabled = enabled == null ? null : enabled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.IS_SYS
     *
     * @return the value of sys_roles.IS_SYS
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public String getIsSys() {
        return isSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.IS_SYS
     *
     * @param isSys the value for sys_roles.IS_SYS
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public void setIsSys(String isSys) {
        this.isSys = isSys == null ? null : isSys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_roles.MODULE_ID
     *
     * @return the value of sys_roles.MODULE_ID
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public String getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_roles.MODULE_ID
     *
     * @param moduleId the value for sys_roles.MODULE_ID
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId == null ? null : moduleId.trim();
    }
}