package org.my.core.common.model;

public class SysResources {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.ID
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.NAME
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.TYPE
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.LEVEL
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.DESCRIPTION
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.URL
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.PARENT_ID
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.STYLE_ID
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    private Integer styleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.PRIORITY
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.ENABLED
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    private String enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.IS_SYS
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    private String isSys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_resources.MODULE_ID
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    private Integer moduleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.ID
     *
     * @return the value of sys_resources.ID
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.ID
     *
     * @param id the value for sys_resources.ID
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.NAME
     *
     * @return the value of sys_resources.NAME
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.NAME
     *
     * @param name the value for sys_resources.NAME
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.TYPE
     *
     * @return the value of sys_resources.TYPE
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.TYPE
     *
     * @param type the value for sys_resources.TYPE
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.LEVEL
     *
     * @return the value of sys_resources.LEVEL
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.LEVEL
     *
     * @param level the value for sys_resources.LEVEL
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.DESCRIPTION
     *
     * @return the value of sys_resources.DESCRIPTION
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.DESCRIPTION
     *
     * @param description the value for sys_resources.DESCRIPTION
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.URL
     *
     * @return the value of sys_resources.URL
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.URL
     *
     * @param url the value for sys_resources.URL
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.PARENT_ID
     *
     * @return the value of sys_resources.PARENT_ID
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.PARENT_ID
     *
     * @param parentId the value for sys_resources.PARENT_ID
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.STYLE_ID
     *
     * @return the value of sys_resources.STYLE_ID
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public Integer getStyleId() {
        return styleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.STYLE_ID
     *
     * @param styleId the value for sys_resources.STYLE_ID
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public void setStyleId(Integer styleId) {
        this.styleId = styleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.PRIORITY
     *
     * @return the value of sys_resources.PRIORITY
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.PRIORITY
     *
     * @param priority the value for sys_resources.PRIORITY
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.ENABLED
     *
     * @return the value of sys_resources.ENABLED
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.ENABLED
     *
     * @param enabled the value for sys_resources.ENABLED
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public void setEnabled(String enabled) {
        this.enabled = enabled == null ? null : enabled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.IS_SYS
     *
     * @return the value of sys_resources.IS_SYS
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public String getIsSys() {
        return isSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.IS_SYS
     *
     * @param isSys the value for sys_resources.IS_SYS
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public void setIsSys(String isSys) {
        this.isSys = isSys == null ? null : isSys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_resources.MODULE_ID
     *
     * @return the value of sys_resources.MODULE_ID
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public Integer getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_resources.MODULE_ID
     *
     * @param moduleId the value for sys_resources.MODULE_ID
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }
}