package org.my.core.common.model;

public class SysStyles {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_styles.STYLE_ID
     *
     * @mbggenerated Sun Mar 15 14:28:04 CST 2015
     */
    private String styleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_styles.STYLE_NAME
     *
     * @mbggenerated Sun Mar 15 14:28:04 CST 2015
     */
    private String styleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_styles.STYLE_CLASS
     *
     * @mbggenerated Sun Mar 15 14:28:04 CST 2015
     */
    private String styleClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_styles.STYLE_CSS
     *
     * @mbggenerated Sun Mar 15 14:28:04 CST 2015
     */
    private String styleCss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_styles.STYLE_DESC
     *
     * @mbggenerated Sun Mar 15 14:28:04 CST 2015
     */
    private String styleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_styles.ICON_NAME
     *
     * @mbggenerated Sun Mar 15 14:28:04 CST 2015
     */
    private String iconName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_styles.ICON_CSS
     *
     * @mbggenerated Sun Mar 15 14:28:04 CST 2015
     */
    private String iconCss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_styles.ICON_DESC
     *
     * @mbggenerated Sun Mar 15 14:28:04 CST 2015
     */
    private String iconDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_styles.REMARK
     *
     * @mbggenerated Sun Mar 15 14:28:04 CST 2015
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_styles.STYLE_ID
     *
     * @return the value of sys_styles.STYLE_ID
     *
     * @mbggenerated Sun Mar 15 14:28:04 CST 2015
     */
    public String getStyleId() {
        return styleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_styles.STYLE_ID
     *
     * @param styleId the value for sys_styles.STYLE_ID
     *
     * @mbggenerated Sun Mar 15 14:28:04 CST 2015
     */
    public void setStyleId(String styleId) {
        this.styleId = styleId == null ? null : styleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_styles.STYLE_NAME
     *
     * @return the value of sys_styles.STYLE_NAME
     *
     * @mbggenerated Sun Mar 15 14:28:04 CST 2015
     */
    public String getStyleName() {
        return styleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_styles.STYLE_NAME
     *
     * @param styleName the value for sys_styles.STYLE_NAME
     *
     * @mbggenerated Sun Mar 15 14:28:04 CST 2015
     */
    public void setStyleName(String styleName) {
        this.styleName = styleName == null ? null : styleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_styles.STYLE_CLASS
     *
     * @return the value of sys_styles.STYLE_CLASS
     *
     * @mbggenerated Sun Mar 15 14:28:04 CST 2015
     */
    public String getStyleClass() {
        return styleClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_styles.STYLE_CLASS
     *
     * @param styleClass the value for sys_styles.STYLE_CLASS
     *
     * @mbggenerated Sun Mar 15 14:28:04 CST 2015
     */
    public void setStyleClass(String styleClass) {
        this.styleClass = styleClass == null ? null : styleClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_styles.STYLE_CSS
     *
     * @return the value of sys_styles.STYLE_CSS
     *
     * @mbggenerated Sun Mar 15 14:28:04 CST 2015
     */
    public String getStyleCss() {
        return styleCss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_styles.STYLE_CSS
     *
     * @param styleCss the value for sys_styles.STYLE_CSS
     *
     * @mbggenerated Sun Mar 15 14:28:04 CST 2015
     */
    public void setStyleCss(String styleCss) {
        this.styleCss = styleCss == null ? null : styleCss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_styles.STYLE_DESC
     *
     * @return the value of sys_styles.STYLE_DESC
     *
     * @mbggenerated Sun Mar 15 14:28:04 CST 2015
     */
    public String getStyleDesc() {
        return styleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_styles.STYLE_DESC
     *
     * @param styleDesc the value for sys_styles.STYLE_DESC
     *
     * @mbggenerated Sun Mar 15 14:28:04 CST 2015
     */
    public void setStyleDesc(String styleDesc) {
        this.styleDesc = styleDesc == null ? null : styleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_styles.ICON_NAME
     *
     * @return the value of sys_styles.ICON_NAME
     *
     * @mbggenerated Sun Mar 15 14:28:04 CST 2015
     */
    public String getIconName() {
        return iconName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_styles.ICON_NAME
     *
     * @param iconName the value for sys_styles.ICON_NAME
     *
     * @mbggenerated Sun Mar 15 14:28:04 CST 2015
     */
    public void setIconName(String iconName) {
        this.iconName = iconName == null ? null : iconName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_styles.ICON_CSS
     *
     * @return the value of sys_styles.ICON_CSS
     *
     * @mbggenerated Sun Mar 15 14:28:04 CST 2015
     */
    public String getIconCss() {
        return iconCss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_styles.ICON_CSS
     *
     * @param iconCss the value for sys_styles.ICON_CSS
     *
     * @mbggenerated Sun Mar 15 14:28:04 CST 2015
     */
    public void setIconCss(String iconCss) {
        this.iconCss = iconCss == null ? null : iconCss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_styles.ICON_DESC
     *
     * @return the value of sys_styles.ICON_DESC
     *
     * @mbggenerated Sun Mar 15 14:28:04 CST 2015
     */
    public String getIconDesc() {
        return iconDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_styles.ICON_DESC
     *
     * @param iconDesc the value for sys_styles.ICON_DESC
     *
     * @mbggenerated Sun Mar 15 14:28:04 CST 2015
     */
    public void setIconDesc(String iconDesc) {
        this.iconDesc = iconDesc == null ? null : iconDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_styles.REMARK
     *
     * @return the value of sys_styles.REMARK
     *
     * @mbggenerated Sun Mar 15 14:28:04 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_styles.REMARK
     *
     * @param remark the value for sys_styles.REMARK
     *
     * @mbggenerated Sun Mar 15 14:28:04 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}