package org.my.core.common.model;

public class SysStyles {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_styles.ID
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_styles.NAME
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_styles.CSS
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    private String css;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_styles.CONTENT
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_styles.DESCRIPTION
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_styles.ICON_NAME
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    private String iconName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_styles.ICON_CSS
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    private String iconCss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_styles.ICON_DESC
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    private String iconDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_styles.REMARK
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_styles.ID
     *
     * @return the value of sys_styles.ID
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_styles.ID
     *
     * @param id the value for sys_styles.ID
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_styles.NAME
     *
     * @return the value of sys_styles.NAME
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_styles.NAME
     *
     * @param name the value for sys_styles.NAME
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_styles.CSS
     *
     * @return the value of sys_styles.CSS
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public String getCss() {
        return css;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_styles.CSS
     *
     * @param css the value for sys_styles.CSS
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public void setCss(String css) {
        this.css = css == null ? null : css.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_styles.CONTENT
     *
     * @return the value of sys_styles.CONTENT
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_styles.CONTENT
     *
     * @param content the value for sys_styles.CONTENT
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_styles.DESCRIPTION
     *
     * @return the value of sys_styles.DESCRIPTION
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_styles.DESCRIPTION
     *
     * @param description the value for sys_styles.DESCRIPTION
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_styles.ICON_NAME
     *
     * @return the value of sys_styles.ICON_NAME
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public String getIconName() {
        return iconName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_styles.ICON_NAME
     *
     * @param iconName the value for sys_styles.ICON_NAME
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public void setIconName(String iconName) {
        this.iconName = iconName == null ? null : iconName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_styles.ICON_CSS
     *
     * @return the value of sys_styles.ICON_CSS
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public String getIconCss() {
        return iconCss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_styles.ICON_CSS
     *
     * @param iconCss the value for sys_styles.ICON_CSS
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public void setIconCss(String iconCss) {
        this.iconCss = iconCss == null ? null : iconCss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_styles.ICON_DESC
     *
     * @return the value of sys_styles.ICON_DESC
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public String getIconDesc() {
        return iconDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_styles.ICON_DESC
     *
     * @param iconDesc the value for sys_styles.ICON_DESC
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public void setIconDesc(String iconDesc) {
        this.iconDesc = iconDesc == null ? null : iconDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_styles.REMARK
     *
     * @return the value of sys_styles.REMARK
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_styles.REMARK
     *
     * @param remark the value for sys_styles.REMARK
     *
     * @mbggenerated Fri Mar 20 13:12:41 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}